services:
  postgres:
    image: postgres:18
    container_name: image-preview-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: image_preview
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: image-preview-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: image-preview-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/storage:/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: image-preview-server
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
      - minio

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: image-preview-worker
    depends_on:
      - postgres
      - rabbitmq
      - minio
